### ISSUE TITLE
questions about paper

### ISSUE THREAD

**Issue by taoqiongxing** [roomylee/entity-aware-relation-classification#2]
Hello,'Figure 4: Visualization of Self Attention' in paper,sentence “the <e1>pollution</e1>was caused
by the <e2>shipwreck</e2>”,pollution is the effect and shipwreck is the cause,so the relation between two entities is Cause-Effect(e2,e1), but in paper,predicting the Cause-Effect(e1,e2),is it correct? Did I misunderstand?

**Comment by roomylee** [comment]
Oh, that's my mistake...😭Class of that sentence is Cause-Effect(e2,e1).
